pennlabs/penn-clubs

components/ClubCard.js, components/ClubDisplay.js, components/ClubTableRow.js, components/common/TagGroup.js, components/common/Tags.js, pages/index.js
There's a question mark after this on the Trello board so maybe this was a waste of time...
On the bright side, I've setup my local dev environment so I can help out with this from now on if need be!
=> Clicking on club card/row tag updates selected tag filters

components/common/TagGroup.js
Check Trello card "Selecting tags sometimes highlights incorrect tags" for details
=> Fix "Selecting tags sometimes highlights incorrect tags"

components/ClubModal/FavoriteButton.js, renderPage.js
See Trello card 'change modal "add favorites" button to "remove from favorites" when it is a favorite': the title is exactly what this is.
=> Implement "change modal "add favorites" button to "remove from favorites" when it is a favorite"

package.json, utils/sentry.js, yarn.lock
=> Use new sentry dependencies

components/Footer/index.js, components/common/Line.js, pages/faq.js
* Slightly cleaner code
* Made a reusable `Line` component
=> Refactor faq

components/ClubModal/Details.js, components/DropdownFilter.js, components/Header/Burger.js, components/Header/index.js, components/common/FavoriteIcon.js, components/common/TagGroup.js
* Hooks
* Default Props
* JSX cleanup
=> Add some hooks

components/Form.js, pages/edit.js, yarn.lock
- Add button to resend an email invitation.
- Requires the corresponding backend PR to also be merged.
=> Add resend button

components/SearchBar.js, package.json, yarn.lock
This is pretty much a 1 to 1 conversion, not much was changed semantically.
=> Convert SearchBar into Functional Component

components/Header/Links.js, components/Settings/ProfileTab.js, static/img/icons/log-out.svg, utils.js
Right now it's in the navbar, but it can be put pretty much anywhere
where put tho
=> Logout Button

components/ClubPage/Header.js, components/Settings/FavoritesTab.js, renderPage.js, yarn.lock
this PR does the title and also removes localstorage usage since users can't see bookmarks unless they're logged in anyway.
=> Bookmarks Persist After Toggle in Profile

components/ClubPage/Actions.js, components/DisplayButtons.js, components/SearchBar.js, pages/index.js
Background is also snow now. Consistency!
=> Style homepage background

README.md, components/ClubPage/InfoBox.js, components/ClubPage/Testimonials.js, components/ClubTableRow.js, components/Form.js, components/Settings/ClubTab.js, components/Settings/ProfileForm.js, components/Settings/ProfileTab.js, components/common/Icon.js, components/common/Typography.js, constants/colors.js, pages/club/[club]/edit.js, pages/club/[club]/fair.js, pages/club/[club]/flyer.js, pages/club/[club]/index.js, pages/index.js, pages/invite/[club]/[invite]/[token]/index.js, pages/settings.js, pages/welcome.js, public/static/img/icons/chevron-up.svg, public/static/img/icons/download.svg, public/static/img/icons/triangle.svg, renderPage.js, utils.js
**Prerequisites**
- Merge after #59 
- Merge after https://github.com/pennlabs/clubs-backend/pull/25, https://github.com/pennlabs/clubs-backend/pull/31, and https://github.com/pennlabs/clubs-backend/pull/34
**Features**
- Implements flyer page(s) with QR code
- Implements club fair page
- Implements school/major/graduation year profile page
- Implements first time login welcome page
- Implements subscriber download page
**Screenshots**
- ![image](https://user-images.githubusercontent.com/4441174/72189281-748c8d00-33ca-11ea-83d5-a9990acdc1e3.png)
- ![image](https://user-images.githubusercontent.com/4441174/72023887-0026e200-3242-11ea-9111-ca1ca7554851.png)
- (old) ![image](https://user-images.githubusercontent.com/4441174/71914389-84486f00-3147-11ea-82f1-29bff8a8db16.png)
- …
=> Implement club fair pages

backend/clubs/admin.py, backend/clubs/management/commands/goap_import.py, backend/clubs/management/commands/goap_update.py, backend/clubs/management/commands/merge_duplicates.py, backend/clubs/management/commands/send_emails.py, backend/clubs/utils.py, backend/clubs/views.py, backend/pennclubs/settings/base.py, backend/tests/clubs/test_commands.py
- Add shared club name matching function to aggressively fuzzy search for a matching club.
- Improve GO@P import script behavior when merging clubs.
=> Improve import script and club name matching

README.md, backend/clubs/urls.py, backend/pennclubs/settings/base.py, backend/pennclubs/settings/production.py, backend/pennclubs/settings/staging.py, backend/pennclubs/urls.py, backend/templates/splash.html, backend/tests/clubs/test_views.py, frontend/next.config.js, frontend/package-lock.json, frontend/package.json, frontend/server.js, frontend/utils.js, k8s/values.yaml
This PR sets up django and next so that they run on the same domain. This reduces the django settings complexity and makes our set up more secure.
For frontend development, you need to set `API_BASE_URL` to http://localhost:3000/api and `LABS_REDIRECT_URI` to http://localhost:3000/api/accounts/callback/
Backend only development doesn't need to set any environment variables.
@ezwang Definitely take a look at the frontend directory and make any changes you need to. @davish can help answer questions for how everything is set up.
=> Merge domains

frontend/components/DropdownFilter.js, frontend/components/SearchBar.js
=> Add Close Icon When Filtering by Tags on Mobile

frontend/components/Form.js, frontend/components/Settings/ProfileForm.js, frontend/pages/club/[club]/edit.js
The submit button in the Form component is disabled until a change is made.
=> Enable Submit Button Only If Changes Were Made

backend/clubs/management/commands/merge_duplicates.py, backend/clubs/models.py, backend/clubs/views.py, backend/pennclubs/settings/base.py, frontend/components/ClubPage/Header.js, frontend/components/Form.js, frontend/components/common/TagGroup.js, frontend/components/common/Tags.js, frontend/package-lock.json, frontend/package.json
- Show umbrella club badges on club page.
- Invert given tag color to ensure text visibility.
- May look better to play around with `lighten` and `darken` depending on the brightness value of the color.
=> Show Badges on Club Page

backend/clubs/mixins.py, backend/clubs/permissions.py, backend/clubs/serializers.py, backend/clubs/urls.py, backend/clubs/views.py, backend/tests/clubs/test_views.py, frontend/components/Form.js, frontend/pages/club/[club]/edit.js
Implement a way for club officers/owners to create/edit/delete testimonials.
=> Testimonials

frontend/components/ClubPage/Actions.js, frontend/renderPage.js
Fixes bug where bookmarks decrement when a user attempts to bookmark a club while not being logged in.
=> Fix Bookmark Decrements Bug

backend/Pipfile.lock, backend/clubs/backends.py, backend/tests/clubs/test_backends.py
This PR updates the custom django backend to log in users to conform to the [current version provided by DLA](https://github.com/pennlabs/django-labs-accounts/blob/master/accounts/backends.py)
=> Update DLA backend

frontend/pages/club/[club]/edit.js
=> This PR maybe fixes club editing

frontend/pages/club/[club]/edit.js, static/img/icons/download.svg
- Currently kinda useless since we don't actually have a way to upload files, but merging this code before it gets too out of date.
=> Add file list to resources tab

backend/Pipfile, backend/Pipfile.lock, backend/clubs/mixins.py, backend/clubs/serializers.py, frontend/package-lock.json, frontend/package.json, frontend/pages/club/[club]/edit.js
- Clubs can see the time that the user subscribed in the subscriber list, as well as the excel spreadsheet download.
=> Add subscription time to subscriber list

frontend/components/Form.js, frontend/package-lock.json, frontend/package.json, frontend/public/static/css/react-datepicker.css
- Firefox does not support `datetime-local`.
- Uses [React Datepicker](https://reactdatepicker.com/) instead to provide date/time picking.
=> Add datepicker for event

frontend/.eslintrc.json, frontend/components/ClubCard.js, frontend/components/ClubDetails.js, frontend/components/ClubTableRow.js, frontend/components/DropdownFilter.js, frontend/components/Form.js, frontend/components/LoginModal.js, frontend/components/SearchBar.js, frontend/components/Settings/ProfileForm.js, frontend/components/TabView.js, frontend/package-lock.json, frontend/package.json
- Complete and merge this when there are no other PRs, this will likely merge conflict with everything.
- Run `prettier --write ./{components,constants,pages}/**/*.js *.js` in the `frontend` folder before merging.
=> Enforce prettier

frontend/components/Form.js, frontend/components/Settings/ProfileForm.js, frontend/package.json, frontend/pages/club/[club]/edit.js, frontend/pages/faq.js, frontend/pages/rank.js
- Add page describing the current club rank algorithm and links to the page on the FAQ and admissions edit form.
- See [here](https://app.clubhouse.io/pennlabs/story/1264/add-page-describing-club-ranking-system) for the story.
=> Add club rank description algorithm

backend/clubs/management/commands/populate.py, backend/clubs/urls.py, backend/pennclubs/settings/base.py, backend/pennclubs/urls.py, backend/tests/clubs/test_commands.py, frontend/components/ClubMetadata.js, frontend/cypress/integration/pages_spec.js, frontend/test.sh
- Add `./manage.py populate` command to make development test data
- Add more test cases with individual clubs
=> Add more test cases

frontend/pages/club/[club]/edit.js
=> Move QR code to resources page

backend/clubs/management/commands/populate.py, backend/tests/clubs/test_commands.py, frontend/cypress.json, frontend/cypress/integration/pages_spec.js, frontend/cypress/support/commands.js
- Add tests with user accounts.
=> Add more tests with users

frontend/Dockerfile
Disable nextjs telemetry so they can't spy on us: https://nextjs.org/telemetry
=> Clubs no phone home

.circleci/config.yml, .gitignore, frontend/.babelrc, frontend/cypress.json, frontend/cypress/plugins/index.js, frontend/cypress/support/index.js, frontend/package.json, frontend/test.sh, frontend/utils/sentry.js, frontend/yarn.lock
Merge https://github.com/pennlabs/orb-react-tools/pull/1 before merging this.
=> Add code coverage to frontend tests

frontend/components/common/Checkbox.js, frontend/components/common/Icon.js, frontend/pages/reports.js
Added back selected fields sidebar for the demo tomorrow
=> Added back selected fields sidebar

frontend/components/Header/Head.js, frontend/components/common/Metadata.js
alright the css is loaded in this time lfg
=> Add Inter (attempt #???)

frontend/components/ClubEditPage.js, frontend/components/ClubPage/Actions.js, frontend/components/FilterSearch.js, frontend/components/Form.js, frontend/components/Settings/ProfileTab.js, frontend/pages/club/[club]/edit.js, frontend/pages/create.js, frontend/pages/reports.js, frontend/yarn.lock
=> Backspace Button Can Delete Tags

frontend/components/DisplayButtons.js, frontend/components/DisplayButtons.tsx
The green on the home page doesn't feel right to me, this makes it the same color as the login button so we maintain visual consistency while also still making the button stand out to the user. Thoughts?
I think we should also change the color of the Edit Club button, or maybe move it under the ellipsis dropdown?
EDIT - @ezwang
=> Make Add Club Button Blue

backend/clubs/views.py, frontend/pages/index.tsx
Mainly re-purposed the `resetDisplay` method in `index.tsx`. Lots of kinda convoluted logic for parsing the checkboxes and turning it into the correct backend query -- let me know if you have ideas on how to clean this up.
Also, made a few small changes to `views.py`. Namely, fixing a bug on parsing the operation, as well as adding supporting for parsing multiple ints (although I think you also added in a solution for this concurrently, when merging I just kept both for good measure because I didn't want to break anything else you might've been working on).
=> Near finalized commit for backend searching

frontend/components/ClubPage/RenewalRequest.tsx, frontend/components/common/Typography.tsx, frontend/constants/routes.ts, frontend/pages/club/[club]/index.tsx, frontend/public/static/img/icons/alert-circle.svg
Added renewal card at the top of all club pages to gear up for renewal process. Left out some of the logic for @ezwang to look at re: renewal schema. 
Side note: am i a frontend dev now?????????????
=> Add renewal request card for all clubs 

backend/clubs/management/commands/deactivate.py, backend/clubs/management/commands/populate.py, backend/clubs/models.py, backend/pennclubs/settings/base.py, backend/tests/clubs/test_commands.py
Add a renewal email that is sent when the deactivate script is run. Also write a test case to ensure that this is the case.
=> Add renewal email to deactivate script

frontend/components/common/TagGroup.tsx, frontend/pages/club/[club]/index.tsx, frontend/types.ts
featuring Knuckles the Echidna
=> Rescue Tag Types 2: Now With More Type Guards

backend/templates/emails/renew.html
=> updated renewal email

frontend/components/common/TagGroup.tsx, frontend/pages/club/[club]/index.tsx, frontend/types.ts
it works I swear
(Featuring Dante From The Devil May Cry Series)
=> Rescue Tags 3: For Real This Time

frontend/components/ClubEditPage/InviteCard.tsx, frontend/components/ClubEditPage/MembersCard.tsx, frontend/types.ts
- Changing permission dropdown updates title input to be the same as the dropdown given that the title text is one of (Member, Officer, Owner) [VIDEO](https://youtu.be/NAD48n0GauA)
- Added a MembershipRole interface that was shared among two files for typescript integration
=> Membership toggle enhancement

backend/clubs/admin.py, backend/clubs/management/commands/deactivate.py, backend/clubs/management/commands/populate.py, backend/clubs/management/commands/rank.py, backend/clubs/serializers.py, backend/clubs/views.py, frontend/components/ClubPage/Actions.tsx, frontend/components/ClubPage/Events.tsx, frontend/pages/club/[club]/index.tsx, frontend/pages/rank.tsx
- Adjust and document the tag rankings
- Show report public status in admin
- Modify populate script to add events
- Add fair_on to list of available report fields
- Allow any field to be ordered for report generation
=> Various improvements

backend/clubs/models.py
[ch2305]
Adds a new event type for the clubs fair
=> Activities Fair Event Type

backend/clubs/management/commands/import_sac.py
Expects a spreadsheet with column titles and the columns `club code, tag, day`.
=> Add command to create SAC fair events

frontend/components/EventPage/EventCard.tsx
[ch2333]
The title says it all. Cover photos won't get loaded until they're one 800px below the viewport. Taken mostly from  `ClubCard.tsx`
=> lazy load cover photos

backend/clubs/management/commands/populate.py, backend/clubs/serializers.py, frontend/components/ClubEditPage/EventsCard.tsx, frontend/components/ClubPage/ListRenewalDialog.tsx, frontend/components/EventPage/EventCard.tsx, frontend/components/FilterSearch.tsx, frontend/components/SearchBar.tsx, frontend/constants/colors.ts, frontend/pages/club/[club]/renew.tsx, frontend/pages/index.tsx, frontend/renderPage.tsx, frontend/utils.tsx
- Allow search by badges (currently limited to superusers)
- Refactor search bar externals/internals to be more portable
- Add `useSetting` stub to control SAC fair settings.
- Remove wording from renewal dialog.
=> Various search improvements

backend/clubs/management/commands/rank.py, backend/clubs/views.py, backend/tests/clubs/test_views.py, frontend/components/SearchBar.tsx, frontend/pages/events.tsx, frontend/pages/index.tsx, frontend/pages/rank.tsx
- Add search to events page, including ability to search by SAC Fair badges.
- All client side ordering.
- Add more tests for server side ordering.
=> Add search to events page

backend/templates/emails/fair_info.html, frontend/components/ClubPage/Actions.tsx, frontend/cypress/integration/request_spec.js
=> Sac fair info email

backend/clubs/mixins.py, backend/clubs/serializers.py, backend/clubs/utils.py, backend/clubs/views.py, frontend/components/common/Typography.tsx, frontend/pages/fair.tsx, frontend/pages/faq.tsx, frontend/pages/rank.tsx
- Add a fair page with list of activities broken down by day
- Modify events to return the badges associated with that club
- Whitelist streamable for embedding
=> Add fair page with list of activities for each day

backend/Pipfile, backend/Pipfile.lock, backend/clubs/management/commands/populate.py, backend/clubs/urls.py, backend/clubs/views.py, backend/pennclubs/settings/base.py, backend/tests/clubs/test_views.py, frontend/components/EventPage/EventCard.tsx, frontend/pages/events.tsx, frontend/pages/index.tsx, frontend/renderPage.tsx, frontend/utils.tsx
- Use the django-runtime-options to implement dynamic settings.
- A bit inefficient as this is loaded on every page, so we should take care to minimize the number of settings we create and ensure they're applicable to multiple pages. The efficiency loss may be negligible, idk.
=> Add server side dynamic options

backend/Pipfile.lock, backend/clubs/consumers.py, backend/clubs/routing.py, backend/pennclubs/routing.py, frontend/components/ClubPage/ChatWidget.tsx, frontend/components/ClubPage/Testimonials.tsx, frontend/pages/club/[club]/index.tsx, frontend/server.js
Chat feature is only visible for superusers.
=> Websockets test with simple live chat functionality

backend/clubs/serializers.py, frontend/components/Form.js
Strongly advise clubs to use Zoom
=> Fair updates

backend/templates/emails/fair_reminder.html, backend/templates/emails/zoom_reminder.html
=> fair reminder

backend/Dockerfile, backend/Pipfile, backend/Pipfile.lock, backend/pennclubs/settings/base.py, backend/scripts/asgi-run, backend/setup.cfg, k8s/values.yaml
=> Split traffic between uwsgi and daphne

backend/Pipfile, backend/Pipfile.lock, backend/scripts/asgi-run
- Switch to Uvicorn, which should be faster and supports multiple workers.
=> Use uvicorn instead of daphne

frontend/components/ClubEditPage.tsx, frontend/components/ClubEditPage/ClubEditCard.tsx, frontend/types.ts
Fixed ones related to school, year, major
=> Typescript conversion

backend/clubs/management/commands/send_emails.py, backend/clubs/models.py, backend/templates/emails/fair_feedback_officers.html, backend/templates/emails/fair_post_virtual.html, backend/tests/clubs/test_commands.py
- Add post fair email script. Send to all events that have passed within last 2 weeks that are part of a fair.
=> Add post fair email script

backend/clubs/management/commands/daily_notifications.py, backend/templates/emails/osa_queue_reminder.html, backend/tests/clubs/test_commands.py, frontend/pages/faq.tsx, k8s/values.yaml
Add a script that emails OSA at 9 AM each day if there are clubs that are pending approval.
=> Add queue reminder script

backend/Pipfile, backend/Pipfile.lock
This PR modifies asgi to use uvicorn standard instead of manually installing deps
=> Uvicorn Standard

frontend/components/ClubDetails.tsx
Added subscribe button in club cards!
There are some layout changes (the Wrapper component adds margin to its not-first children = icons) but it's quite flexible, we could add more icons later if we need to.
Screenshot below for preview
=> [Feature] Subscribe button in cards

frontend/components/EventPage/DateInterval.tsx
Calculate the time difference from a new moment object instead of the original one. previously, the startOf function was applied to the string that is being displayed.
=> Start date

backend/clubs/serializers.py, backend/tests/clubs/test_views.py
- Automatically expand google calendar copied urls into the original url
- Add a check to ensure that the end time is always greater than the start time
- Remove old blacklisted site
=> Add more event time/url validation

frontend/components/Header/Links.tsx, frontend/components/SearchBar.tsx, frontend/constants/measurements.ts
- Fixes [this issue](https://app.clubhouse.io/pennlabs/story/2605/text-escapes-navbar)
- Before
- ![image](https://user-images.githubusercontent.com/4441174/95680360-141fbb80-0ba7-11eb-87e7-77190a974829.png)
- After
- ![image](https://user-images.githubusercontent.com/4441174/95680365-24379b00-0ba7-11eb-9251-f56f1963d8c3.png)
=> Fix issue with header overflow on certain screen size

.circleci/config.yml, k8s/values.yaml
This PR deploys the FYH (currently just a copy of penn clubs but with a separate db and secrets)
=> Deploy FYH

frontend/pages/rank.tsx
Adding space to this line: "You can easily renew your clubfrom the settings tab in the manage club page" at https://pennclubs.com/rank.
=> Newline fix

backend/clubs/management/commands/populate.py, backend/clubs/models.py, backend/tests/clubs/test_models.py, frontend/components/Header/Feedback.tsx, frontend/components/Header/index.tsx, frontend/cypress/integration/superuser_spec.js, frontend/pages/club/[club]/renew.tsx, frontend/pages/directory.tsx, frontend/pages/faq.tsx, frontend/pages/index.tsx, frontend/utils/branding.tsx
- Add year alternative names ("first year" and "second year").
- Fix the home page to be full height even with little clubs.
- Add partner logos based on the current site.
- Change the feedback URL to the new one.
- Fix the scaling when hovering over the header logo.
=> Hub@Penn Styling Fixes

backend/clubs/views.py, frontend/Dockerfile, frontend/constants/colors.ts, frontend/cypress/integration/superuser_spec.js, frontend/package.json, frontend/pages/settings.tsx, frontend/yarn.lock
- Change settings page background for now to a more appropriate gradient for now
- Changing this to an image is not too easy, multiple backgrounds need to be set on different elements
- Fix massive N+1 issues on bookmarks/subscribes/memberships pages.
=> Change settings gradient and SQL efficiency gains

frontend/components/ClubEditPage.tsx, frontend/components/ClubEditPage/PotentialMemberCard.tsx, frontend/components/ClubPage/Actions.tsx, frontend/cypress/integration/superuser_spec.js, frontend/pages/faq.tsx, frontend/utils/branding.tsx
- Add membership request deletion button
- Fix membership request and subscription card description duplication
- Make manage club button more reliable
- Fix FAQ for Hub@Penn
[ch2455] [ch2807]
=> Add membership request deletion button and fix FAQ for Hub@Penn

frontend/pages/club/[club]/index.tsx
- Added signature events field. The field is only rendered for resources.
[ch2780]
=> signature-events

backend/clubs/management/commands/rank.py, backend/clubs/views.py, frontend/components/ClubEditPage.tsx, frontend/components/ClubEditPage/DeleteClubCard.tsx, frontend/components/ClubPage/Actions.tsx, frontend/components/ClubPage/ClubApprovalDialog.tsx, frontend/components/FormComponents.tsx, frontend/components/Settings/QueueTab.tsx, frontend/pages/club/[club]/edit.js, frontend/pages/club/[club]/index.tsx, frontend/pages/club/[club]/renew.tsx, frontend/pages/rank.tsx, frontend/pages/renew.tsx, frontend/pages/reports/index.tsx, frontend/renderPage.tsx, frontend/utils.tsx
- Revamp permissions system to request permissions all in bulk on page load.
- Modify rank to take into account not modifying the subtitle and tweak values a bit.
- Fix minor typos.
=> Revamp permissions system

backend/clubs/views.py, frontend/components/ClubEditPage/AnalyticsCard.tsx
Partial redesign on club analytics page. New features:
- Time series data points are smaller
- You can group in time series data (by hour, day, week, month)
- Colors for pie charts
- Now only one pie chart, which you can select a category and metric for to get your desired pie chart
Please feel free to tear apart the typescript! I am very open to suggestions lol.
[ch2361][ch2465]
=> Analytics Partial Redesign

backend/templates/emails/fyh_emails/approval_status.html, backend/templates/emails/fyh_emails/base.html, backend/templates/emails/fyh_emails/owner.html, backend/templates/emails/fyh_emails/question.html, backend/templates/emails/fyh_emails/remind.html
- changed wording, copy from FYH box page
- Unsure if this will work with base email directory atm, wasn't able to see previews on /api/emailpreview 
[ch2822]
=> FYH Email templates

backend/clubs/views.py, backend/tests/clubs/test_views.py, frontend/components/ClubEditPage/DeleteClubCard.tsx, frontend/pages/club/[club]/edit.js, frontend/utils.tsx
- Modify permissions lookup to be more efficient in bulk.
- Add more specific permission for club deletion.
- Add Django test case for permissions endpoint.
- Add ability to pass multiple permissions (OR) to check at once.
=> Permissions fixes

backend/clubs/serializers.py, frontend/components/ClubEditPage/ClubEditCard.tsx, frontend/components/Settings/ProfileForm.tsx, frontend/pages/faq.tsx, frontend/pages/rank.tsx, frontend/utils/branding.tsx
- Allow no Undergraduate/Graduate tags if they don't exist.
- Fix branding on profile form component.
- Fix spacing issues.
=> Various small Hub@Penn fixes

frontend/components/ClubEditPage/ClubEditCard.tsx, frontend/constants/colors.ts, frontend/pages/index.tsx, frontend/types.ts, frontend/utils/branding.tsx
- Add recruiting cycle field on Penn Clubs (not on Hub@Penn).
[ch2842]
=> Add recruiting cycle field to frontend

backend/clubs/views.py
- Event from unapproved clubs are filtered
=> Filter events from unapproved clubs

frontend/components/ClubEditPage/InviteCard.tsx, frontend/components/ClubEditPage/MembersCard.tsx, frontend/components/ClubPage/LiveEventsDialog.tsx, frontend/components/Settings/ClubTabTable.tsx, frontend/components/Settings/RenewTabTable.tsx, frontend/utils/branding.tsx
- Rename "Officer" -> "Editor", "Member" -> "Viewer" in Hub@Penn.
- Rename "Members" -> "Staff".
[ch2837]
=> Update wording for owner/officer/member on Hub@Penn

frontend/components/ResourceCreationPage.tsx
=> Add text on intro page

frontend/components/ClubEditPage/EventsCard.tsx, frontend/components/ClubPage/Events.tsx, frontend/components/EventPage/EventCard.tsx, frontend/components/EventPage/EventModal.tsx, frontend/pages/events.tsx
`isHappening` is used in `EventCard` and `EventModal` as a property, but it was quite redundant since we could also compare `new Date()` with `event.start_time` and `event.end_date` to see if an event is happening now or not.
=> [Refactor] removed isHappening as a prop

backend/clubs/models.py, backend/clubs/serializers.py, backend/templates/emails/confirmation.html, backend/templates/fyh_emails/confirmation.html, backend/templates/fyh_emails/invite.html, backend/tests/clubs/test_views.py, frontend/components/ClubEditPage/ClubEditCard.tsx
- incl. confirmation emails
[ch2836]
=> Hub emails (including confirmation)

frontend/utils/branding.tsx
=> Fix FYH feedback link

frontend/components/ClubEditPage/AnalyticsCard.tsx, frontend/components/ClubEditPage/DeleteClubCard.tsx, frontend/components/ClubEditPage/FilesCard.tsx
Missed this in the last PR, included it here.
[ch2871]
=> Updated Branding for Delete Card

frontend/components/reports/ReportForm.tsx, frontend/pages/reports/index.tsx, frontend/utils.tsx
- Add the ability to filter clubs by badge when generating reports.
=> Add badges filter for reports

backend/clubs/serializers.py, backend/clubs/views.py, backend/tests/clubs/test_views.py, frontend/components/FilterSearch.tsx, frontend/components/FormComponents.tsx, frontend/components/reports/ReportForm.tsx, frontend/components/reports/ReportPage.tsx, frontend/components/reports/ReportTable.tsx, frontend/constants/routes.ts, frontend/package.json, frontend/pages/reports/[report]/index.tsx, frontend/pages/reports/create.tsx, frontend/pages/reports/index.tsx, frontend/utils.tsx, frontend/yarn.lock
=> Refactor reports to remove race condition

backend/clubs/views.py
- required for ICS module
- added 1 second delta if equal
[ch2885]
=> Equality check for start and end times

backend/clubs/views.py
- added more validation for older events in the database
- restricted timeline to show past events only from 30 days ago and onwards 
- if time equal, changed timedelta to 15 minutes to appear bigger on calendar interface
=> Ics hotfix

backend/clubs/admin.py, backend/clubs/management/commands/daily_notifications.py, frontend/components/ClubEditPage/InviteCard.tsx, frontend/components/ClubEditPage/MembersCard.tsx, frontend/components/Settings/ClubTabTable.tsx, frontend/pages/settings.tsx, frontend/utils.tsx, frontend/utils/branding.tsx
- Convert settings form from a class component to a functional component.
- Remove the Viewer role from Hub@Penn.
- Use OSA group for emails instead of hardcode.
[ch2869] [ch2876] [ch2845]
=> Misc changes

frontend/components/ResourceCreationPage.tsx
=> Move points of contact to first page of creation on Hub@Penn

backend/clubs/management/commands/send_emails.py, backend/clubs/management/commands/set_emails.py, backend/clubs/models.py, backend/clubs/utils.py, backend/templates/fyh_emails/intro.html, backend/templates/fyh_emails/owner.html, backend/tests/clubs/test_commands.py, frontend/components/ClubEditPage/ClubEditCard.tsx, frontend/components/Settings/QueueTab.tsx, frontend/components/common/Checkbox.tsx, frontend/components/reports/ReportForm.tsx, frontend/pages/renew.tsx
=> Add intro email templates for Hub@Penn

backend/clubs/urls.py, backend/clubs/views.py, backend/tests/clubs/test_views.py
- End-to-end test case to test database inconsistencies between production and local (resolution: uuid function behavior differed in local and in production)
- tests filter query's user retrieval and time filter
- retrieves ICS file, parses and checks if contents are appropriate
[ch2896]
=> Added end-to-end test case for ICS endpoint

backend/clubs/management/commands/populate.py, backend/clubs/views.py, frontend/components/ClubEditPage/MembersCard.tsx, frontend/components/ClubPage/InfoBox.tsx, frontend/components/ModelForm.tsx, frontend/components/common/Icon.tsx, frontend/package.json, frontend/types.ts, frontend/yarn.lock, penn-clubs.code-workspace
Features
- Show recruitment cycle on club page
- Add shortcuts to VSCode for launching Hub@Penn
- Allow officers to configure the active status of members
- Finish making a table component with pagination, searching, and ordering. Use `react-table` to make this easier.
[ch1102]
=> Misc improvements

frontend/components/ClubEditPage/AdvisorCard.tsx, frontend/components/ModelForm.tsx, frontend/components/ResourceCreationPage.tsx
- Not Complete
- Disable continue if there are no public contacts while creating resources
- Add onUpdate prop for ModelForm to update parent component
[ch2838]
=> Require contact

frontend/components/EventPage/DateInterval.tsx, frontend/components/FilterSearch.tsx, frontend/components/Footer/index.tsx, frontend/components/SearchBar.tsx, frontend/components/common/Typography.tsx, frontend/constants/colors.ts, frontend/pages/directory.tsx, frontend/pages/events.tsx, frontend/public/static/css/fyh.css, frontend/scripts/gen_css.py
- Improve text color contrasts on home page, events page, FAQ page, and directory page.
- Meet AA accessibility requirements.
- Improve scrolling behavior of search sidebar to be more smooth.
- Add screen reader labels to buttons with icons in them.
- Add comments for CSS generation script.
=> Hub@Penn accessibility changes

backend/clubs/management/commands/send_emails.py, backend/clubs/serializers.py, backend/clubs/views.py, backend/templates/fyh_emails/intro_remind.html, frontend/components/ClubEditPage/ClubEditCard.tsx, frontend/components/SearchBar.tsx, frontend/pages/faq.tsx
- Efficiency improvements.
- Better user inputs.
- Add user search endpoint to backend.
- Minor FAQ fixes.
- Update email template.
=> Various fixes

frontend/components/ClubEditPage/ClubFairCard.tsx, frontend/components/FormComponents.tsx, frontend/components/ResourceCreationPage.tsx
- Add form inputs for text/multi line text/rich text
- Add changes requested by Hub@Penn
=> Add additional dynamic form inputs

backend/Pipfile.lock, backend/clubs/management/commands/populate.py, backend/clubs/serializers.py, backend/clubs/views.py, frontend/pages/constitutions.tsx, frontend/server.js
- Possibly has a few edge cases we still need to handle.
=> Add page for checking if SAC clubs have uploaded constitution

frontend/components/EventPage/SyncModal.tsx, frontend/components/Header/Head.tsx, frontend/package.json, frontend/pages/_app.tsx, frontend/pages/events.tsx, frontend/public/static/img/icons/clipboard.svg, frontend/yarn.lock
The modal UI is ready, just need some more detail on how ics export will work and we'll be good to go.
* looking for a clean way to implement copy; should we just stick with `navigator.clipboard api`?
* need confirmation on the directions to be written!
[ch2741]
=> ICS Calendar Export UI

backend/clubs/serializers.py, backend/clubs/urls.py, backend/clubs/views.py, backend/tests/clubs/test_views.py, frontend/cypress/integration/invite_spec.js, frontend/cypress/integration/request_spec.js
- Add more coverage for backend.
- Modify the email invitation endpoint so that it can also be used for production purposes.
=> Improve test cases

backend/clubs/admin.py, backend/clubs/permissions.py, backend/clubs/views.py, frontend/components/EventPage/CoverPhoto.tsx, frontend/components/Settings/ClubTab.tsx, frontend/components/Settings/Toggle.tsx, frontend/components/common/Modal.tsx, frontend/constants/routes.ts, frontend/cypress/integration/request_spec.js, frontend/pages/club/[club]/alumni.tsx, frontend/pages/club/[club]/index.tsx, frontend/pages/club/[club]/org.tsx, frontend/pages/settings.tsx, frontend/pages/user/[user]/index.tsx, frontend/public/static/img/icons/database.svg, frontend/public/static/img/icons/git-branch.svg, frontend/utils/branding.tsx
- Fix inconsistent toggle behavior.
- Transition `confirm` to a proper modal.
=> Various bugfixes on membership settings

backend/clubs/consumers.py, backend/clubs/management/commands/find_broken_images.py, backend/clubs/management/commands/rank.py, backend/clubs/management/commands/sync.py, backend/clubs/routing.py, backend/clubs/views.py, backend/tests/clubs/test_channels.py, frontend/pages/admin.tsx
- Use websockets to execute scripts, allowing for long running scripts and real time output.
=> Use websockets to execute scripts

backend/templates/fyh_emails/second_round.html
=> Change comma placement

backend/clubs/views.py, frontend/components/ClubEditPage/ApplicationsCard.tsx, frontend/components/ModelForm.tsx, frontend/components/Settings/FairEventsTab.tsx, frontend/components/Settings/FairsTab.tsx, frontend/pages/admin.tsx, frontend/pages/fair.tsx, frontend/pages/fairs.tsx, frontend/public/static/img/icons/eye.svg
- Add a tab to view events related to the club fair and whether or not they are configured.
- Add a link to preview the club fair on the management table.
[ch3007]
=> Improve fair dashboard

backend/Pipfile.lock, backend/clubs/views.py, frontend/components/FilterSearch.tsx, frontend/components/Settings/FairEventsTab.tsx, frontend/components/Settings/MembershipRequestsTab.tsx, frontend/components/Settings/QueueTab.tsx, frontend/components/common/Tags.tsx, frontend/pages/admin.tsx, frontend/pages/events.tsx, frontend/pages/faq.tsx, frontend/pages/renew.tsx, frontend/utils.tsx, frontend/yarn.lock
- Bump deps.
- Add fair events tab to admin page.
- Better permissions checking on admin tabs.
- Add ability to filter by club on events page.
- Cache the public endpoints used on the events page.
- Add empty state text for tables.
- Update FAQ to fix spacing issues, nested `<p>` and `<ul>` tag issues.
=> Minor fixes

backend/clubs/management/commands/send_emails.py, backend/templates/fyh_emails/communication_to_partners.html
=> Hub@Penn Partner Communication Email

backend/clubs/consumers.py, backend/clubs/management/commands/send_emails.py, backend/clubs/views.py, frontend/components/ClubPage/InfoBox.tsx, frontend/components/FormComponents.tsx, frontend/components/Header/Feedback.tsx, frontend/components/Header/index.tsx, frontend/components/PaginatedClubDisplay.tsx, frontend/components/common/Metadata.tsx, frontend/pages/admin.tsx, frontend/pages/club/[club]/fair.tsx, frontend/pages/club/[club]/index.tsx, frontend/pages/index.tsx, frontend/utils/branding.tsx
- Add links between Penn Clubs and Hub@Penn when there are no search results.
- Update social media `og:image` metadata tags.
- Replace the feedback button with a scroll up button on Hub@Penn.
- Fix animation for feedback button on Penn Clubs.
- Hide the information box if there is no information.
- Fix bug with email template rendering with no arguments.
=> Hub changes

backend/clubs/views.py
Verify whether incoming post request from Zoom is valid
=> Verify the Authorization header in the Zoom Webhook

.gitignore, backend/clubs/admin.py, backend/clubs/models.py, backend/clubs/views.py, frontend/components/EventPage/EventModal.tsx, frontend/components/ResourceCreationPage.tsx, frontend/constants/routes.ts, frontend/pages/fair.tsx, frontend/pages/faq.tsx, frontend/pages/zoom.tsx
- simple FAQ updates with links to Hub/Clubs redirecting users to the other resource
=> FAQ updates for hub/clubs

backend/clubs/management/commands/send_emails.py, backend/clubs/models.py, backend/clubs/views.py, backend/templates/emails/fair_info.html, backend/templates/emails/question.html, backend/templates/preview.html, frontend/components/EventPage/EventModal.tsx, frontend/components/Settings/FairEventsTab.tsx, frontend/markdown/fair.md
- Update virtual activities fair email (make generic and remove old text).
- Update guide to use the automated process only.
- Update email script to use test flags.
- Update email preview to modify variables with plain JSON.
=> Update virtual activities fair email

frontend/components/ClubEditPage/AnalyticsCard.tsx
=> Analytics timeseries patch

README.md, backend/clubs/models.py, backend/clubs/serializers.py, frontend/components/ClubEditPage/ClubEditCard.tsx, frontend/components/ClubPage/Actions.tsx, frontend/components/common/Typography.tsx, frontend/pages/club/[club]/apply.tsx, frontend/pages/club/[club]/index.tsx, frontend/pages/index.tsx
- Modify signature events and how to get involved fields to be rich text fields.
- Requested by Hub@Penn.
- Ensure that #378 is merged before this branch is merged.
=> Rich fields

backend/clubs/models.py, backend/clubs/serializers.py, backend/clubs/views.py, frontend/components/ClubEditPage.tsx, frontend/components/ClubEditPage/AdvisorCard.tsx, frontend/components/ClubEditPage/ClubEditCard.tsx, frontend/components/ClubEditPage/EventsImportCard.tsx, frontend/components/ClubEditPage/InviteCard.tsx, frontend/components/ClubEditPage/QuestionsCard.tsx, frontend/components/EmbedOption.tsx, frontend/components/EventPage/SyncModal.tsx, frontend/components/FormComponents.tsx, frontend/components/ModelForm.tsx, frontend/components/ResourceCreationPage.tsx, frontend/components/TabView.tsx, frontend/cypress/integration/authed_spec.js, frontend/cypress/integration/invite_spec.js, frontend/cypress/integration/request_spec.js, frontend/pages/admin.tsx, frontend/pages/club/[club]/edit/[[...slug]].tsx, frontend/pages/club/[club]/renew.tsx, frontend/pages/fairs.tsx, frontend/pages/renew.tsx, frontend/pages/settings.tsx, frontend/pages/zoom.tsx, frontend/renderPage.tsx
- Fix model form issue with not updated from server provided response values.
- Allow users to show/hide Q&A requests and responses.
- Make the answer field for Q&A rich text.
- Refactor edit page to use query parameters instead of hashes for tabs.
- Modify the embed object functionality to autocorrect iframe embeds.
- Rename snake case variables to camel case.
[ch3065]
=> Form fixes

frontend/components/ClubEditPage/ClubEditCard.tsx, frontend/components/common/Checkbox.tsx, frontend/components/common/Icon.tsx, frontend/types.ts
=> Add checkbox gateway for membership restrictions

backend/clubs/management/commands/import_paideia_events.py, backend/pennclubs/settings/production.py, k8s/values.yaml
[ch3269]
Create a script to import events from https://snfpaideia.upenn.edu/wp-json/wp/v2/event into the Events model.
Modify cron job to do this at a set frequency.
=> Import Paideia Events

backend/clubs/views.py, frontend/pages/index.tsx
Users can switch between exclusive filtering and general filtering on H@P
=> Exclusive view on H@P

backend/clubs/permissions.py, backend/clubs/urls.py, backend/clubs/views.py, frontend/components/ClubEditPage.tsx, frontend/components/ClubEditPage/ClubManagementCard.tsx, frontend/utils/branding.tsx
=> Add ability for umbrella organizations to edit badges

backend/clubs/views.py, frontend/pages/index.tsx, frontend/types.ts
Not quite sure if this matches the requirements from fyh, but let me know if there's anything that I forgot to take care of!
=> Search result divider

backend/clubs/management/commands/populate.py, frontend/pages/apply.tsx, frontend/pages/club/[club]/application/[application]/index.tsx
* Application due date included under the title.
* Cursor changes to a pointer when hovering over a Wharton club application on the `/apply` page. imo more intuitive but either works.
=> app due date and pointer on hover over wharton club application

backend/clubs/serializers.py, backend/clubs/views.py, backend/tests/clubs/test_views.py
Fix image upload bug by changing keyword arg for request payload in helper function
=> Image Upload Bug Fix

backend/clubs/management/commands/populate.py, backend/clubs/models.py, backend/clubs/serializers.py, backend/clubs/views.py, frontend/components/ClubEditPage/ApplicationsPage.tsx, frontend/components/common/Table.tsx
Added download to CSV functionality as well as some other bug fixes, primarily in the club officer reading view
=> Download to CSV

frontend/components/ClubDetails.tsx, frontend/components/ClubDisplay.tsx, frontend/components/common/SubscribeIcon.tsx, frontend/pages/index.tsx
Story: 2594
* Fixed inconsistent bookmark and subscriber states when clicking between list and card view
* Added context provider for displayed clubs (to update state without reloads), would be good to get some other frontend opinions on the design choice!
=> List bug fix

backend/clubs/management/commands/populate.py, backend/clubs/serializers.py, backend/clubs/urls.py, backend/clubs/views.py, frontend/components/ClubCard.tsx, frontend/components/ClubEditPage/ApplicationsPage.tsx, frontend/components/Settings/WhartonApplicationStatus.tsx, frontend/components/common/Checkbox.tsx, frontend/components/common/Table.tsx, frontend/constants/routes.ts, frontend/pages/wharton/[[...slug]].tsx, frontend/types.ts
Data visualizations in react are my worst nightmare
=> Application Status View for Wharton Council

frontend/pages/index.tsx
- Hid the school and year filters for Penn Clubs, these should only be viewable in hub@penn.
=> hide filters in clubs

frontend/pages/club/[club]/index.tsx
- Quick fix on searchable select
=> fix on searchable select

frontend/components/ClubEditPage/ApplicationsPage.tsx
Cringe but it works. I think our table component in `common/Table` should support selectable rows as a feature (just feels like there are so many use cases), I'll play around with it.
=> temp button to select all applications

k8s/values.yaml
The ghost of @ezwang still haunts us
=> Fix k8s values typo

backend/clubs/serializers.py
=> Update create method to resolve admin note id issue

backend/clubs/migrations/0091_pgcrypto.py, backend/clubs/views.py
Import postgres crypto to use SHA1
=> Bug Fix for Randomly Seeding Wharton applications

k8s/main.ts
=> Scale up for Wharton Club Fair

frontend/pages/index.tsx, k8s/main.ts
Scale down and remove `LiveCustomDialog` banner that reflected outage
=> Scale down after Wharton Club Fair

backend/clubs/migrations/0091_cryptoextension.py, backend/clubs/views.py
Active Wharton Council applications are currently [displayed to users](https://pennclubs.com/apply) in the same order each time. This change randomizes that order by user.
=> Randomly order active Wharton apps (should be fixed from #547)

frontend/components/ClubEditPage/ApplicationsPage.tsx
- Made the applicants page scrollable.
- Put scroll bar on top
=> applicants page style improvment

frontend/components/Applications.tsx
- No mixing, looks good so far.
=> Apply page patch

frontend/components/FormComponents.tsx
=> Update uuid import from default

frontend/components/Announcement.tsx, frontend/pages/_app.tsx
=> temp:(banner)

frontend/pages/club/[club]/application/[application]/index.tsx
=> Add hour to displayed application deadline

README.md
=> Add testing instructions to readme

backend/clubs/views.py
Also replaces previous logic to grab event names with `select_related` as per @julianweng's insistence.
=> Fix breaking changes to `cart` in #670

backend/clubs/permissions.py, backend/clubs/views.py, backend/tests/clubs/test_ticketing.py
Adds route for club admins to issue tickets to users. Tickets must already be created to be issued.
=> Add route for admins to issue tickets to users

backend/clubs/management/commands/expire_membership_invites.py, backend/clubs/management/commands/find_broken_images.py, backend/clubs/management/commands/update_club_counts.py, backend/clubs/models.py, backend/clubs/serializers.py, backend/tests/clubs/test_views.py
Changelog: 
1. Merge master into ticketing
2. Remove unused Ticket attribute (when was this introduced?)
=> Merge master into ticketing

backend/clubs/serializers.py
Necessary for the ticket scanner to determine whether a ticket is attended or not
=> Add attended field to TicketSerializer

frontend/components/ClubEditPage/EventsCard.tsx, frontend/components/ModelForm.tsx, frontend/pages/events/[id].tsx
Fixes issue of creating tickets immediately following event creation by calling onChange on object creation for ModelForm. Also fixes image dimension issues on new event page.
=> Fix ticketing event creation and image on event page

frontend/pages/club/[club]/renew.tsx
Update club renewal info as per OSA's request
=> Update renewal info

.github/workflows/build-and-deploy.yaml, backend/clubs/serializers.py, backend/clubs/views.py
Reverts pennlabs/penn-clubs#727
=> Revert "Hide approved=False clubs"

.github/workflows/build-and-deploy.yaml, frontend/bun.lock, frontend/package.json
* Add back frontend check for lint purposes
* Bump deprecated action versions across CICD
=> Restore frontend check, bump action versions

frontend/pages/club/[club]/renew.tsx
Updates policies encountered in registration and re-registration flows.
=> Update OSA policies

frontend/bun.lock, frontend/components/ClubEditPage/AnalyticsCard.tsx, frontend/components/Settings/WhartonApplicationStatus.tsx, frontend/package.json
Removed react-vis, replaced with recharts
=> New charting library
