components/ClubCard.js
components/DropdownFilter.js
static/img/icons/box-blue.svg
static/img/icons/box-red.svg
static/img/icons/box-yellow.svg
static/img/icons/box.svg
static/img/icons/check-box-blue.svg
static/img/icons/check-box-red.svg
static/img/icons/check-box-yellow.svg
static/img/icons/check-box.svg

They were removed when I ported over to feather-icons, now I added em back:

Add colored check boxes (back)

---

components/ClubPage/SocialIcons.js
components/ClubPage/SocialLink.js

Uses a regex to strip "https" and "www" from social urls.
Maybe we could format social urls in specific ways (for example, displaying twitter page links as @twitterusername) instead?

Strip Social Urls to Decrease Their Length

---

components/TabView.js
pages/club/[club]/index.js

This PR moves the fetch for club info on the club detail page into the `getInitialProps` call. Now, nextjs will render all club details server-side and send the page to the client. This is preferable for a few reasons:
1. SEO -- web crawlers will now get all the HTML for the page without having to run JS (which they don't do very well)
2. Speed -- before, the page needed to load + render before the backend was queried for club data. Now, the browser gets the HTML right away in the original request.
Relevant documentation for reading more: https://nextjs.org/docs#fetching-data-and-component-lifecycle

Render Club Page Server Side

---

frontend/components/ClubCard.js
frontend/components/ClubDisplay.js
frontend/components/ClubTableRow.js
frontend/components/common/TagGroup.js
frontend/pages/index.js

Club tags no longer have the ability to add or remove selected filters

Kill Club Card Tag Filtering

---

frontend/renderPage.js

Delete old csrftoken cookie on every page load. Fixes bug with old token shadowing the current working cookie. This code should be removed in a year or so.

Delete old csrftoken cookie

---

backend/clubs/models.py
backend/clubs/serializers.py
backend/clubs/views.py
backend/pennclubs/settings/base.py
backend/pennclubs/settings/ci.py

Club list is regenerated in another thread when a club is edited.

Regenerate Clubs List Cache on Club Modification

---

frontend/components/common/Grid.js

Should fix the name overflow issue by truncating with ellipses - more sustainable solution is a WIP

Member card width/padding bug

---

.circleci/config.yml

Bump the helm-tools orb to allow slack notifacations to the #deployments channel on successful deploys.

Bump helm-tools

---

frontend/components/ClubCard.js
frontend/components/ClubPage/Actions.js
frontend/components/TabView.js

- Remove the "more" ellipses on club pages that weren't doing anything
- Stop tracking tabs in history –– tracking in state is enough and this removes the need for tons of back-button pressing

Small fixes

---

README.md

This repo contains several symlinks, which aren't reproduced on Windows by Git by default due to security reasons. Adds info to the Development section of the README on how to enable symlinks in development for Windows users.

Add Info About Symlinks to README

---

backend/Pipfile
backend/Pipfile.lock
frontend/components/Header/Links.js
frontend/pages/club/[club]/index.js
frontend/renderPage.js

This PR adds cookie forwarding to requests in `getInitialProps` to remove the need to send AJAX requests once the page loads on the client. User data and individual club data will be loaded in on the NextJS server, and sent in the initial HTML payload to the client.
This gets rid of any flicker on page load.

Render authenticated data on first page load

---

backend/clubs/management/commands/deactivate.py
backend/clubs/views.py
frontend/pages/club/[club]/renew.tsx

Added:
- `/renew` detail endpoint for clubs that sets `active=true
- `deactivate` command that sets `active=false` for all clubs (be careful with this one!)
- Renew form now posts to renewal endpoint to clubs are set to active after finishing the form

Renewal backend

---

frontend/components/Form.js
frontend/components/Settings/ProfileForm.js

One thing that's confusing with this change is that the upload image button requires you to press save, whereas the delete image button deletes the image straight up, without needing the user to press save. Maybe I should edit the Form component so that you can have a file upload field that shows two buttons when the field is uploaded, one of which sets [name]: null like the delete profile pic button was doing before, instead of "injecting' the button like I did here? lmk what y'all think.

Move Delete Profile Picture Button

---

frontend/components/ClubPage/Header.tsx
frontend/components/common/TagGroup.tsx
frontend/pages/club/[club]/index.tsx

So I figured out why the tags disappeared, turns out there was a switch statement that expects the kind property of a tag object to be populated with either "tag" or "badge", so I added a default branch and now tags show up.
However, from looking at the TS types, I suspect that somewhere in the frontend or the backend the tag objects should be annotated with the kind property containing either the string value of "tag" or "badge". Should I annotate the objects, and should it be on the backend (in a Serializer or smth) or on the frontend?

[WIP] Rescue Club Tags

---

frontend/components/ClubEditPage.tsx
frontend/components/ClubEditPage/EventsCard.tsx
frontend/components/ClubPage/Actions.tsx
frontend/components/ClubPage/ClubApprovalDialog.tsx
frontend/cypress/integration/superuser_spec.js
frontend/pages/rank.tsx

[ch2241]
This PR makes some small tweaks to the edit page.
1. Changes button from `Edit Club` to `Manage Club`, since a lot more happens besides editing club details.
2. Moves events into its own tab on the club management page. Before it was buried at the bottom of "Resources".
There were also some other small tweaks, like renaming "Information" to "Edit Club Information". I also hid the mobile preview, since we don't currently have any mobile integration, it might be confusing for the SAC fair.
3. The Membership tab now includes the components for inviting new members, accepting/rejecting membership requests, and viewing/managing existing memberships. The QR code is now in the recruitment tab, since it's used during recruitment season. Not sure if the ordering of invite, requests, …

Club Management Page Modifications

---

backend/clubs/serializers.py
backend/clubs/urls.py
backend/clubs/views.py
backend/tests/clubs/test_views.py

[ch2250]
This PR adds some new endpoints for events, and gets rid of the requirement that events be namespaced to clubs.
The `test_event_list` testcase is also expanded to test these endpoints.
You can now get all events at `/api/events`, and can still get a club's events at `/api/club/[club]/events`.
- `/events` will get all events that haven't finished yet.
- `/events/live` will get all events which are currently happening (current time between start & end times).
- `/events/upcoming` will get all events which have not yet started.
- `/events/ended` will get all events that have end times in the past.

Event Endpoints

---

backend/clubs/views.py

Realized that the last PR used `datetime.datetime.now()` instead of `timezone.now()`, which is a no-no in django when timezone support is on (the default). This PR fixes that.

hotfix to use django timezones instead of raw datetime

---

backend/clubs/urls.py
backend/clubs/views.py
frontend/components/ClubPage/MemberList.js
frontend/cypress/integration/invite_spec.js

- Quick bug fix of public/private status. The club page was displaying user's who were private
[Before VIDEO](https://youtu.be/-Sm2TDi8_0A)
[After fix VIDEO](https://youtu.be/zTaOPYThleI)
- Added endpoint /test/lastemail that displays the club code, invite id, token only in development
- Added cypress testing for club invitation
[VIDEO](https://youtu.be/JZHTJJ4Pa-0)

Invite Cypress Testing complete

---

backend/clubs/permissions.py
backend/clubs/views.py
backend/tests/clubs/test_views.py
frontend/components/Form.js

- Can't create an event with the activity fair type
- Can't change an existing event from or to that type
- Form.js will show DRF validation errors now
- Test to make sure I dont break things
- only show fair events on the /events page (TODO: remove this after fair)

Fair Event Security

---

backend/clubs/filters.py
backend/clubs/serializers.py
backend/clubs/views.py
backend/tests/clubs/test_views.py
frontend/components/ClubCard.tsx
frontend/components/ClubPage/Description.tsx
frontend/components/ClubPage/Events.tsx
frontend/components/EventPage/CoverPhoto.tsx
frontend/cypress/integration/authed_spec.js

- Add backend for searching through events through `club__` selectors.
- Separate out random ordering and pagination system into separate file.
- List endpoint now only returns subtitle if it exists, or short description if it does not. This is all that is used by the frontend.
- Remove `target_*` fields from list view, no longer being used by the frontend.
- Style fixes for events cards.

Add backend for searching through events

---

frontend/pages/index.tsx

Just so we don't forget to do this on Tuesday :)
Banner won't show up until events start happening on Tuesday, since the `/live` endpoint is currently filtered to only include events for the club fair

Enable events banner

---

backend/clubs/views.py
frontend/pages/fair.tsx
frontend/pages/zoom.tsx

- Pages are starting to feel a little bit slow, add in some caching to make it better.
- Rewrite `/fair` page calculations to be on server side.
- Require authentication for `/zoom` page.

Add caching to events pages

---

frontend/pages/club/[club]/index.tsx

[ch2302]
This PR adds a button to club pages to allow visitors to jump directly to the Q&A (which can be buried pretty far below the fold). It also puts Q&A above members, but let me know if we want to reverse that.
Wondering about what the copy should be here... Both of the options (no questions and questions having been asked) are kind of wordy. Open to suggestions on this one

jump to Q&A from sidebar

---

backend/clubs/admin.py
backend/clubs/views.py
frontend/pages/fair.tsx

Add a date parameter for the fair page that simulates the fair page display on a certain date.
Will be used for recreating a screenshot of the SAC fair page.

Add date parameter for fair page

---

backend/clubs/serializers.py
backend/clubs/views.py
frontend/components/ClubDetails.tsx
frontend/components/ClubPage/InfoBox.tsx
frontend/types.ts

Use real member counts instead of relying on clubs to put their own approximate member counts.
May want to consider showing the old club size field while people switch over.

Use real member counts

---

backend/clubs/views.py

Literally wrote like 20 characters, but look at the number of queries decrease!
Problem was that we were using fields from the `Profile` model (image, has_been_prompted, graduation_year, etc.) in the `MembershipSerializer` without prefetching that model.
[ch2772]

Resolved members n+1 slowdown issue

---

frontend/utils/analytics.tsx
frontend/utils/branding.tsx

Added the two tracking codes to the `branding.tsx` file and setup `analytics.tsx` to use the imported tracking code from branding.

Branding Google Analytics tracking code switch

---

backend/clubs/views.py
frontend/components/ClubEditPage/AdvisorCard.tsx
frontend/components/Form.js

Separate the point of contact form for public and private contacts. Still allows you to switch between the two with a checkbox, this behavior may be confusing and it might be a good idea to remove it.
[ch2749]

Separate point of contact form

---

backend/clubs/urls.py
backend/clubs/views.py
frontend/components/ClubEditPage.tsx
frontend/components/ClubEditPage/ClubEditCard.tsx
frontend/pages/club/[club]/edit.js
frontend/pages/club/[club]/renew.tsx
frontend/pages/index.tsx
frontend/renderPage.tsx
frontend/types.ts
frontend/utils/branding.tsx

- Add student type field to the frontend (club edit page, search sidebar).
- Only load student type field if enabled for the site (using branding constants).
[ch2747]

Add student type field frontend

---

backend/clubs/views.py
frontend/components/FilterSearch.tsx
frontend/components/SearchBar.tsx
frontend/components/common/Tags.tsx
frontend/constants/colors.ts
frontend/pages/index.tsx

- Fix issue with tag text colors not being properly rendered.
- Separate out tag colors for tags and badges.
- Add in tag colors for school, school year, and student type.
- @snie11 we may want to color these differently, send me color scheme for Penn Clubs / Hub@Penn if this is the case.
- Fix issue with duplicate key not rerendering element on top tags section.
[ch2778]

Fix tag styling issues

---

backend/clubs/serializers.py
backend/clubs/urls.py
backend/clubs/views.py

[ch2843]
– Added backend endpoint to retrieve a user's UUID
– Used for ICS Calendar export

Added backend endpoint to retrieve a user's UUID

---

frontend/components/DisplayButtons.tsx
frontend/components/DropdownFilter.tsx
frontend/components/FilterSearch.tsx
frontend/components/Header/Links.tsx
frontend/components/Header/index.tsx
frontend/components/OrderInput.tsx
frontend/components/SearchBar.tsx
frontend/components/common/Grid.tsx
frontend/components/common/ProfilePic.tsx
frontend/constants/measurements.ts
frontend/pages/index.tsx

- Fix scrolling issue with the sidebar on Hub@Penn. Uses the window scroll event, can be made much more efficient.
- <img src="https://user-images.githubusercontent.com/4441174/98719058-3ef36000-235d-11eb-98f2-b6419991d6a5.png" width="300" />
- Fix issues with search bar rendering improperly for Penn Clubs and Hub@Penn. This design isn't optimal, but at least it is usable.
- Ensure that background image is not shown on mobile view, even after scrolling.
- Ensure that padding is correct for logo in Hub@Penn mobile view.
- ![image](https://user-images.githubusercontent.com/4441174/98719345-a14c6080-235d-11eb-94b2-9bf95e330961.png)
- Fix issues with the navbar being the wrong color, make the navbar item vertical space smaller on mobile, and fix the issue with the background being the wrong …

Lots of minor mobile fixes

---

frontend/components/ClubEditPage/AnalyticsCard.tsx
frontend/components/ClubEditPage/FilesCard.tsx

Updated Branding:
- Analytics page entirely updated
- Updated `club` to be abstracted in the FilesCard
- No changes made to the DeleteCard, I double checked and this looks good but if there is something that needs to be changed here, let me know and I can do that
[ch2841][ch2871]

Updated branding on Analytics page and Files page

---

backend/clubs/management/commands/populate.py

Updated test data for events:
- Spans two weeks forward and backward
- Alternates days with overlapping events (30 minute overlap) and zero overlap events
- 10 events for each day
[ch2853]

Populate Events

---

backend/clubs/serializers.py
backend/clubs/views.py
backend/pennclubs/settings/base.py
backend/tests/clubs/test_views.py
frontend/components/ClubCard.tsx
frontend/components/ClubEditPage/InviteCard.tsx
frontend/pages/settings.tsx
frontend/utils/branding.tsx

- Remove Requests tab from settings page for Hub@Penn
- Make only one tag required in Hub@Penn instead of either "Graduate" or "Undergraduate" tags
- Don't include rejected clubs on the directory
[ch2875]

Hub@Penn changes

---

.github/dependabot.yml

Manually configure dependabot for both subdirectories to keep our dependencies up to date. See details [here](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-dependabot-version-updates).
@ArmaanT thoughts on this method?

Manually configure dependabot for both subdirectores

---

backend/clubs/admin.py
backend/clubs/serializers.py
backend/clubs/views.py
backend/tests/clubs/test_views.py

- Admins (people with approval permissions) bypass the approval process when editing clubs.
- Global permissions override per object permissions. If a user has `clubs.manage_club`, they also have `clubs.manage_club:*`. This behavior is currently not used.

Permissions changes

---

backend/clubs/serializers.py
frontend/components/ClubEditPage/AdvisorCard.tsx
frontend/components/ClubEditPage/ClubEditCard.tsx
frontend/components/ClubPage/RenewalRequestDialog.tsx
frontend/components/Footer/index.tsx
frontend/components/Header/Feedback.tsx
frontend/components/ModelForm.tsx
frontend/components/ResourceCreationPage.tsx
frontend/components/Settings/QueueTab.tsx
frontend/pages/club/[club]/index.tsx
frontend/pages/club/[club]/renew.tsx
frontend/pages/faq.tsx
frontend/utils/branding.tsx

- Add accessibility link in footer of Hub@Penn
- Add a warning to add "http://" or "https://" in front of the URL for websites, or the form will not work.
- Allow people who can manage the club to go through the approval process, even if they are not a member of the club (superusers can now approve).
- Add a list of clubs that are in the inactive state to the queue approval page.
- Update the wording after the initial form submission on the Hub@Penn creation page to be less confusing.
- Add the required steps to move on to the next page at the bottom of the page for the 2nd resource creation page.
- Add "noopener" and "noreferrer" to Airtable and Penn links.
[ch2923] [ch2920] [ch2913]

Various Hub@Penn fixes

---

backend/clubs/permissions.py
backend/clubs/views.py
backend/tests/clubs/test_views.py

Removes pending clubs that a user is a member of from the club list.
Not sure if this will fix the issue, but if it's a SQLite vs postgres issue this might be the one way to check easily for it.
This PR means that club owners won't be able to see their pending clubs in the main list anymore, but they'll still see it on their user profile page.

Remove special case in club list queryset

---

backend/clubs/permissions.py
frontend/constants/routes.ts
frontend/pages/guides.tsx

- Add extremely simple list page for guides.
- Allow people with `clubs.see_fair_status` to perform edits.

Add guides list page

---

backend/clubs/serializers.py
backend/clubs/views.py
backend/pennclubs/doc_settings.py
backend/pennclubs/urls.py
backend/templates/redoc.html
backend/tests/clubs/test_admin.py
backend/tests/clubs/test_commands.py
backend/tests/clubs/test_models.py
backend/tests/clubs/test_security.py

- Add metadata and images.
- Categorize endpoints roughly based on the URL.
- Convert camel case to title case.

Make backend documentation a bit nicer

---

backend/clubs/models.py
backend/clubs/urls.py
backend/clubs/views.py
backend/pennclubs/doc_settings.py
backend/pennclubs/settings/base.py
backend/pennclubs/urls.py
backend/tests/clubs/test_admin.py
backend/tests/clubs/test_documentation.py
backend/tests/clubs/test_security.py

- Add a method to add OpenAPI specification using docstrings using YAML.
- Apply this method to all of the `@detail` endpoints.
- Add a test to ensure that all `@detail` endpoints have appropriate documentation.
- Ensure that there are no `operationId` conflicts.
- Fix ICS, populate and accept more fields such as uuid, creation/modified time, and url.
[ch2967]

Add lots of backend documentation

---

backend/clubs/management/commands/send_emails.py
backend/templates/fyh_emails/second_round.html

- Add the second round email template and script for contacting resources at Hub@Penn.
- To run this in production, we would ssh into the machine, run the `./manage.py send_emails hap_second_round emails.csv`.
- You must have a `emails.csv` file which is a CSV file with the columns `name`, `email`, where name is the resource name and email is the contact responsible for the resource. Manually format the Excel document provided by Hub@Penn into this format and upload it using something like `cat` and copy paste.
[ch2972]

Add Hub@Penn second round email

---

frontend/next.config.js
frontend/utils.tsx

This PR configures clubs to use a [next runtime config](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration) that will allow us to dynamically provide a DOMAIN/SITE_ORIGIN to use.
The idea is that nothing will change in production, but we will be able to run integration tests in CI using docker-compose (integration tests must be run on localhost because of CORS/CSRF issues)

Use a runtime config

---

frontend/components/SearchBar.tsx
frontend/pages/events.tsx

- Search bar has a toggle button now instead of always being on.
- Events page buttons use floats instead of flexbox, so they resize better when the screen shrinks.
- Could be improved, but makes the page more usable.

Improve search and events page on mobile

---

.circleci/config.yml
frontend/Dockerfile
frontend/next.config.js
frontend/utils/branding.tsx
k8s/values.yaml

This PR adds an additional runtime config option that allows us to define the frontend styling. This means we can run both clubs and hub from the same docker images.

Even more runtime config

---

frontend/components/ClubEditPage/RenewCard.tsx
frontend/components/ClubPage/ClubApprovalDialog.tsx
frontend/components/ClubPage/ListRenewalDialog.tsx
frontend/components/Settings/RenewTab.tsx
frontend/pages/club/[club]/renew.tsx
frontend/pages/user/[user]/index.tsx
frontend/utils.tsx

- The approval process should be performed every school year, not every calendar year.
- Update the calculations to calculate the proper school year during a winter semester.

Use school year instead of calendar year

---

backend/Pipfile
backend/Pipfile.lock
backend/pennclubs/doc_settings.py

https://jsonref.readthedocs.io/en/latest/
This just ensures that any refs in the schema don't cause issues with manual changes to the schema. This was an issue in the penn-courses docs after an update (parts of the schema contain "$ref": "/path/to/other/place/" key/value pairs which cause errors if the code assumes the referenced section is present).

Handle JSON refs

---

backend/clubs/models.py
backend/clubs/views.py
frontend/pages/zoom.tsx
frontend/utils/sentry.tsx

- List all of the upcoming virtual fairs as the subtitle instead of just the most recent one.
- Use toasts for notifications instead of embedded notifications.
- Ensure that an ICS event cannot become an activities fair event.
- Fix minor text spacing issues and update wording to be more clear.

Minor tweaks to Zoom page

---

backend/clubs/management/commands/send_emails.py
backend/clubs/models.py
backend/clubs/serializers.py
backend/clubs/views.py
backend/templates/emails/fair_info.html
backend/tests/clubs/test_views.py
frontend/pages/zoom.tsx

- If the user has linked their Zoom account and the URL is a Zoom URL, then we should allow them to perform any modifications they want.
- Add a catch statement if the fix meeting fails so that the user isn't wondering what went wrong.

Allow modification of zoom URL

---

backend/clubs/permissions.py
backend/clubs/views.py
frontend/cypress/integration/invite_spec.js
frontend/pages/invite/[club]/[invite]/[token]/index.tsx
frontend/renderPage.tsx

Redesign according to: https://www.figma.com/file/VVeUyX2YmUc4hhGh2a9pSk/Invite-Page?node-id=0%3A1
Related clubhouse story: https://app.clubhouse.io/pennlabs/story/2934/invite-page-redesign
Desktop(>900px):
Mobile(<900px):
* Still needs a way to handle decline invitation

Invite page redesign

---

frontend/components/RouteProgressBar.tsx
frontend/pages/_app.tsx

Some pages take a bit to load and I thought it might be a good idea to entertain the user with a progress bar while the page is loading new resources.
This uses next.js's router events to simulate "progress" (which really isn't, it's just a pseudo-progress based on start-complete state events) and its real purpose is to just tell the user that nothing is really frozen, it's just stuff happening in the background.
Inspired by YouTube I guess?
If you want a higher resolution preview, here's the original screen recording: https://user-images.githubusercontent.com/62971511/107964328-8177a900-6fec-11eb-85f2-d70fb937c4be.mov

Route Progress Bar

---

backend/templates/fyh_emails/ics_calendar_ingestation.html
frontend/components/ClubEditPage/ClubEditCard.tsx

Weekly Hub Changes

---

backend/clubs/management/commands/send_emails.py
backend/clubs/management/commands/wharton_council_application.py
backend/templates/emails/update_status_reminder.html

Wharton Council wants us to send out a reminder email to all Wharton Council clubs telling them they have to update their decision statuses for application submissions.

Status Reminder Email for Wharton Council

---

backend/Pipfile
backend/Pipfile.lock
backend/clubs/models.py
backend/clubs/permissions.py
backend/clubs/serializers.py
backend/clubs/views.py
backend/pennclubs/settings/base.py
frontend/components/ClubEditPage/ApplicationsCard.tsx
frontend/components/ModelForm.tsx
frontend/pages/club/[club]/application/[application]/index.tsx

**Short Summary**
This is a mega PR that aims to address the following [critical] requests from Wharton Council: 
• make sure that it is easy for clubs to create their applications (and maybe even copy them from previous years)
• prevent the problem of them accidentally deleting their application like last semester.
• make sure that each application is limited to 500 words per committee,
• see that each applicant is only allowed to apply to two committees per club.
**Detailed Summary**
**Tests/rollout/revert plan**
- I will add test cases for backend functionality (clone/committee applications) before merging

Wharton Council Fixes

---

backend/clubs/admin.py
backend/clubs/models.py
backend/clubs/serializers.py
backend/clubs/views.py
frontend/components/ClubEditPage/ApplicationsCard.tsx
frontend/components/ClubEditPage/ApplicationsPage.tsx
frontend/pages/club/[club]/apply.tsx
frontend/types.ts
frontend/utils.tsx

This PR is aimed at building upon #566 and adding a bunch of cleanup / efficiency improvements. A list of changes is below:
- Admin page supports better querying over application submissions and application cycles
- The @property season is now deprecated, with existing code migrated to use application cycles instead; season is used as a fallback to preserve backwards compatibility
- Caching is added to the `retrieve` endpoint for the generic club API. (`clubs/<club_code>`).
- Fixed a bug in the `/questions` endpoint which included archived submissions
- Added an endpoint (`/current`) to `ClubApplicationViewSet` used to retrieve ongoing applications. This is used in `club/<club_code>/apply` to only show the active application.
- Prefetching added to `ClubApplicationViewset`
- Rework …

General Improvements / Fixes

---

backend/clubs/views.py

The regex for matching zoom links allowed for non-domain formats.
For example the following could match:   https://fredazoomaus/j/123/pwd=
See the link below for fix invalidation
https://regex101.com/r/xPe7AD/1

Adding escape character to zoom link regex

---

frontend/components/ClubPage/InfoBox.tsx
frontend/types.ts

`InfoBox` uses `membership_count` which does not exist anymore. `membership_count` should be removed from `Club` type definition. Seems like `InfoBox` is the only component making use of this property, so we might as well delete it, but I marked it as deprecated for safety. See [types.ts](https://github.com/pennlabs/penn-clubs/blob/fix/registered-count/frontend/types.ts#L176).

fix: Deprecate membership_count

---

.pre-commit-config.yaml
backend/clubs/views.py
frontend/components/ClubEditPage/ApplicationsPage.tsx

Creates an option for club admins to resend all acceptance/rejection emails, regardless of whether applicants have been previously notified or not. Resolves #585. 
Still a WIP. To-do: 
What it looks like:

wip-feature: Allow resend of acceptance/rejection emails

---

backend/clubs/models.py
backend/clubs/views.py

Previously, we would create new `ApplicationSubmission` and `ApplicationQuestionResponse` objects every time a user submitted their application; this change ensures that each user will have at most one submission per application per committee.
Going forward, we should be able to remove raw SQL queries like [this](https://github.com/pennlabs/penn-clubs/blob/2814025e7853a02bfe2ac2431a2013f910f00ec7/backend/clubs/views.py#L5290C21-L5299C78) since users won't have multiple submissions associated with an application, but this would be potentially problematic for past applications unless we run a script that drops all submissions that aren't the most recent.

Upsert Application Submissions

---

backend/pennclubs/settings/production.py

Django 4.2 deprecated the previous API for django-storages. This PR brings us up to date.

Fix django storages API

---

backend/pennclubs/settings/development.py

Fixes CSRF breaking in dev due to Django 4.0: [https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins](https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins)

Whitelist dev localhost from CSRF

---

frontend/renderPage.tsx

Adds a limit to the # of pop-up notifications on screen at once. Also closes previous notifications faster. Here's a [before](https://github.com/pennlabs/penn-clubs/assets/69180850/2aa85098-b5dd-49a0-8134-86de3ede181e) vs [after](https://github.com/pennlabs/penn-clubs/assets/69180850/7cbbc573-6c44-4105-be6e-5b26bf7d0d68).
Requesting a review to make sure this is a desired change.

Style Toastify notifications

---

backend/clubs/views.py
frontend/pages/admin/[[...slug]].tsx

Add frontend check (on top of backend) for relevant permissions to access /admin.

Fix admin page access on frontend.

---

backend/pennclubs/settings/production.py

Aligns S3 storage config with pre #617 styling, while using the new API.

Streamline django storages config

---

frontend/pages/settings.tsx

The logged-in user's display name is empty in some cases, such as when you're a student taking a leave of absence. This change will display the PennKey if the user's name is an empty string.

Display username in profile page if name is empty

---

frontend/components/SearchBar.tsx

Bumps debounce timeout to 400ms. Tested locally & the search still felt snappy and responsive. 
There's definitely a more data-driven way to do this, but 400ms seems to check out. Supposedly [the average characters per minute for an adult is 200](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjZwdvs3oCFAxV5ElkFHYoADUwQFnoECA0QAw&url=https%3A%2F%2Fwww.typingpal.com%2Fen%2Fdocumentation%2Fschool-edition%2Fpedagogical-resources%2Ftyping-speed&usg=AOvVaw20sNp_Pgw5UaKZz5_WTKSu&opi=89978449), which means 300ms per keystroke. Our previous debounce timeout was below this, so we were effectively querying for every keystroke.

Bump debounce timeout to 400ms

---

backend/clubs/views.py
backend/templates/emails/club_deletion.html

We've seen a couple cases where a club is deleted but its owners aren't notified. This PR adds support for sending emails to club owners (and the executors of deletions) upon deletion requests. 
Not sure whether the email template looks fine (and I'm not sure how to check, either). Also unsure whether this should be a method in `models`.

Notify club owners upon deletion

---

backend/clubs/views.py

Resolves edge case where the user initiates checkout, but waits 15 mins (i.e. longer than the hold, but shorter than the capture context expiration).

Check ticket holds before completing checkout

---

backend/clubs/views.py
frontend/components/ClubEditPage/TicketsModal.tsx

Adds price field to list/add views for tickets in any given event. Integrates price field into club admin ticket creation page.

Ticketing price integration

---

backend/tests/clubs/test_views.py

This PR aims fix the #662, by checking that that the tested expiry datetime is within 5 minutes of the invite's expires_at datetime

Fix intermittent failure of tests introduced in #624

---

frontend/package.json
frontend/pages/settings.tsx
frontend/yarn.lock

We're seeing breaking changes in prod because of an error in this PR. Reverting it for now.

Revert "Move submissions from /apply to user profile"

---

backend/clubs/views.py
backend/tests/clubs/test_ticketing.py

Changelog: 
1. Refactors total price summation to an internal helper function. Adds tests for it. (Previous code was failing but wasn't caught, since we mock `initiate_checkout` and `complete_checkout`. Breaking this logic into its own, testable function will hopefully catch future mistakes.)
2. Adds tests for creating tickets with group discounts.
3. Adds tests for summing a cart total with group discounts applied. 
4. Only populates `sold_out` if there are tickets that were not replaced.
5. Aligns tests with changes introduced in ^ and #670.

Fix backend tests for group discounts, new cart API, and more

---

backend/clubs/management/commands/expire_membership_invites.py
backend/clubs/management/commands/find_broken_images.py
backend/clubs/management/commands/update_club_counts.py

Will hopefully prevent [similar errors](https://penn-labs.slack.com/archives/C05UD8MF894/p1713729310377469).

Improve error reporting in mgmt cmds

---

backend/clubs/serializers.py

We've gotten complaints from OSA that admin reports are missing certain fields (e.g. `created_at`, `target_majors`, `accepting_members`, etc.). This PR should solve.
[without fix](https://github.com/pennlabs/penn-clubs/files/15103894/unfixed_w_all_fields.xlsx) vs [with fix](https://github.com/pennlabs/penn-clubs/files/15103896/fixed_w_all_fields.xlsx)

Fix empty fields in generated admin reports

---

backend/clubs/models.py
backend/templates/emails/ticket_confirmation.html

Adds QR code image as an attachment to the ticket confirmation email. Gmail does not display embedded base64 images, which is why the QR code was not previously showing up.

Fix QR code not showing up in Gmail

---

frontend/components/Settings/TicketTransferModal.tsx

Reminds users that transfer recipients must have a valid PennClubs account.

Add note to ticket transfer flow

---

frontend/components/Settings/TicketsTab/index.tsx
frontend/components/Tickets/TicketCard.tsx

- Removes action buttons when ticket stack for given event is collapsed.
- Adds numbering to ticket when stack is collapsed and has multiple tickets in it
- Removes numbering for "stacks" with only one ticket in it
Attempts to make it clearer when multiple tickets are owned that the stack is expandable, differentiating it visually from single owned tickets.

Make multiple owned tickets UI more intuitive

---

backend/clubs/models.py
backend/pennclubs/settings/base.py

The majority of replies to our automated emails related to club approval/re-approval are best handled by OSA (e.g. "When would X club be approved?"). CC'ing them for each email (so recipients can reply all) is unnecessary and asking recipients to email OSA instead of replying might be unreliable: keeping the instruction to reply to the email but setting reply-to to include OSA seems like a reasonable change.

Set reply-to to OSA email for approval-related notification emails

---

backend/pennclubs/settings/production.py

Sample 10% of transactions [as discussed](https://penn-labs.slack.com/archives/C05UD8MF894/p1716834205819349).

Reenable Sentry monitoring with lower sample rate

---

backend/clubs/models.py
backend/tests/clubs/test_models.py

Adds retry logic to handle one-off SMTP errors. Seems to primarily affect membership requests. [[1](https://penn-labs.sentry.io/issues/5414670480/?end=2024-05-27T23%3A59%3A59&project=6171867&query=&referrer=issue-stream&start=2024-02-29T00%3A00%3A00&stream_index=3&utc=true), [2](https://penn-labs.sentry.io/issues/4820156177/?end=2024-05-27T23%3A59%3A59&project=6171867&query=&referrer=issue-stream&start=2024-02-29T00%3A00%3A00&stream_index=5&utc=true)]

Add retry logic for SMTP errors

---

backend/clubs/management/commands/daily_notifications.py
backend/clubs/serializers.py
backend/pennclubs/settings/base.py
backend/tests/clubs/test_commands.py
backend/tests/clubs/test_views.py
frontend/components/ClubEditPage/ClubEditCard.tsx
frontend/components/ClubPage/LiveEventsDialog.tsx
frontend/components/FormComponents.tsx
frontend/utils/branding.tsx

Per OSA request, disables editing of club fields that would necessitate queue approval as well as daily email notifications for queue approval.

Disable queue for summer

---

backend/clubs/models.py
backend/clubs/views.py
backend/tests/clubs/test_ticketing.py

Add tests left out from ticketing

---

backend/clubs/models.py
backend/clubs/views.py
backend/tests/clubs/test_ticketing.py

-Remove TODO
-Test that transaction record create when `_give_tickets()` is called

Resolve unaddressed nits in #703

---

backend/clubs/management/commands/daily_notifications.py
backend/clubs/serializers.py
backend/pennclubs/settings/base.py
backend/tests/clubs/test_commands.py
backend/tests/clubs/test_views.py
frontend/components/ClubEditPage/ClubEditCard.tsx
frontend/utils/branding.tsx

Per OSA request:
* Opens approval queue solely for edits to existing clubs, keeping club creation closed
* Disables approval queue entrance on editing club description
Also:
* Fixes bug where creating new clubs on backend doesn't check for approval queue status

Partially open queue for Fall 2024

---

frontend/pages/user/[user]/index.tsx

Currently, for signed in users, visiting a user profile set to private yields a slightly different page compared to profiles that don't exist, which implicates the existence or nonexistence of any given Pennkey and associated email at `/user/{pennkey}`. This would theoretically let someone scrape the vast majority of Penn emails in existence through brute force, including those hidden from the Penn directory and email autocompletes.
I'm not sure if this is necessary or outweighs the marginal benefit of the error detail, and we should discuss separately, but am opening a PR since it's a one line change.

Remove error details for hidden user profiles

---

backend/clubs/management/commands/deactivate.py
backend/tests/clubs/test_commands.py

Adds cache invalidation to deactivation script. Adds test case that checks whether cached clubs are flushed after running deactivation command. 
For context: we run a command to deactivate all clubs at the beginning of the year. This kicks off the renewal cycle. The command changes club attributes but doesn't invalidate the cache. This results in incorrect behavior -- the frontend marks clubs as having been approved prematurely.

Invalidate cache after deactivation in renewal flow

---

frontend/components/common/TagGroup.tsx

There are sometimes collisions between tags and badges on a club's main page. (See the attached file for an example.) This PR adds filtering logic on the frontend to 1) only display one badge per unique label 2)  in the event of a conflict between a badge and a tag, display the badge. 
Credit to @jamesdoh0109 for spotting this.

Don't display duplicate badges and tags

---

backend/clubs/serializers.py
backend/clubs/views.py
backend/pennclubs/settings/ci.py
backend/tests/clubs/test_views.py

Deactivated clubs are displayed differently to permissioned vs non-permissioned users. Users without permissions are expected to see the last approved version; users with permissions see the most up-to-date version. Currently, caching in the viewset incorrect caches the non-permissioned state and displays it to permissioned users. This leads to approval messages showing up in the club management dashboard, despite the club not being approved. 
This PR adds a test to check this case (should fail with current code), and adds a fix. It also turns on caching in CI.

Fix permission-related display issues after club deactivation

---

frontend/components/common/TagGroup.tsx

Should fix badges of different colors being scattered throughout a club's page.

Group badges by color in club page

---

frontend/components/ClubPage/Actions.tsx
frontend/pages/club/[club]/application/[application]/index.tsx
frontend/pages/club/[club]/index.tsx

Currently, if a user is unauthenticated, the apply button does not display even if the club's application is open (leading to some confusion). Additionally, enforces auth for viewing club applications.

Display apply button to unauthenticated users

---

frontend/components/ClubEditPage/ApplicationsPage.tsx

Currently, the Manage Clubs > Applications Page view defaults to the first application cycle created for each club (see below). This is not ideal because when club leaders wish to see their applications page, it is almost always in order to view the most recent application, and creates a slower user flow because we first load all of the applications from the oldest application cycle.
This PR reverses the order of applications shown on the Applications Page tab and sets the default application to be the most recent cycle.

Show newest application cycle first in edit club view

---

.github/workflows/build-and-deploy.yaml
backend/clubs/serializers.py
backend/clubs/views.py

Prevents clubs which have been explicitly dis-approved by admins from showing up in search or having an individual club page visible to non-admins.

Hide approved=False clubs

---

backend/clubs/models.py

Replaces duplicated logic across notification flows.

Use Club.get_officer_emails() to send alerts

---

backend/clubs/management/commands/graduate_users.py
backend/tests/clubs/test_commands.py
backend/tests/clubs/test_views.py
k8s/main.ts

The `graduate_users` script, which deactivates memberships for users who graduated before the current year, was originally intended to be executed manually via the admin console. Since this task should occur automatically at the beginning of each year, it makes more sense to have the script as a cronjob.

Move graduate_users script to cronjob

---

backend/clubs/models.py
backend/clubs/views.py
backend/templates/emails/approval_status.html
backend/templates/emails/club_deletion.html

Modifies email templates to remove unnecessary language. Adds language telling clubs to contact OSA. Modifies sent message to direct replies to OSA. 
Screenshots below (left is before, right is after):

Change email templates

---

backend/clubs/serializers.py
backend/clubs/views.py
frontend/components/ClubEditPage.tsx
frontend/components/ClubEditPage/AdminNoteCard.tsx

Adds a tab under the club management page for site admins to add notes about clubs as per OSA's request. Previously, site admins could only use interact with notes via the backend.

Admin note frontend

---

frontend/components/DisplayButtons.tsx
frontend/components/Header/Burger.tsx
frontend/components/Header/Links.tsx
frontend/components/Header/index.tsx

This PR does a couple things to make the user flow a little clearer:
1. Shows the login button on the navbar for mobile users versus hidden in the menu, making it more obvious when users aren't signed in (we have received support requests where users were simply not signed in on mobile but were unaware)
2. Rename the "Add Club" button to "Register Club" to make its purpose more specific and signals the fact that Penn Clubs is the official OSA-sponsored platform for new clubs to register on
3. Makes the login button equally spaced with the other links in desktop view (this one is gratuitous)
Before/After (Desktop)
Before/After (Mobile)

Increase authed/non-authed clarity for mobile view, change wording on "Add Club" button

---

backend/clubs/views.py
backend/tests/clubs/test_ticketing.py
frontend/components/Tickets/CartTickets.tsx
frontend/pages/events/[id].tsx

Adds various frontend and backend tweaks to behavior in the case where an event has elapsed.

Add checks for elapsed events in ticketing

---

backend/clubs/permissions.py
backend/clubs/views.py
backend/templates/emails/blast.html
backend/tests/clubs/test_ticketing.py

Adds support for email blasts from event owners to ticket holders. I'm envisioning using this for an admin feature as well (ex: OSA wants to send a message to all club leaders, like they did at the start of this semester). 
Here's what an event-related email might look like:

Add support for (ticket) email blasts

---

frontend/components/Settings/WhartonApplicationStatus.tsx

I fixed the wharton/status page. I know you want me to fix the cycles page. However, I don't yet have access to the cycles page on Penn clubs website and the one on localhost just points to a create cycle component.

Wharton Dashboard fixes

---

backend/clubs/views.py

As mentioned in #722, the CSV export for application submissions is currently cached, which leads to unintended staleness issues particularly when club leaders download a "final" list of following a period of many submissions (e.g. WC deadline), which may not be included in the cached copy. As speedup from caching is likely minimal (only one or two people are exporting any given application's submissions anyways and they implicitly expect an up-to-date copy regardless), we can just remove the caching for now.

Disable cache for application submission exports

---

backend/clubs/models.py
backend/clubs/serializers.py
backend/clubs/views.py
backend/tests/clubs/test_ticketing.py
backend/tests/clubs/test_views.py
frontend/components/ClubEditPage/EventsCard.tsx
frontend/components/ClubEditPage/QuestionsCard.tsx
frontend/components/ClubEditPage/TicketsModal.tsx
frontend/components/ClubPage/QuestionList.tsx
frontend/components/EmbedOption.tsx
frontend/components/EventPage/EventCard.tsx
frontend/pages/events/[id].tsx
frontend/pages/events/index.tsx
frontend/pages/tickets/[[...slug]].tsx
frontend/types.ts
frontend/utils.tsx

* Add UI support for ticket drop times
* Add `ticket_drop_time` validation in event serializer based on event end time
* Prevent retroactive editing of ticket drop time after tickets have been sold (plus handling of edge case where ticket has been added to cart but not bought before ticket drop time is pushed back)
* Prevent unapproved clubs from selling tickets (add_to_cart)
* Prevent clubs which have been archived from selling existing tickets
* Allow leaders of unapproved clubs to create and view events (with the warning that such events are not visible to the public until the club is approved), allowing for "draft" functionality (also currently, the event just disappears after submission on the frontend for unapproved clubs...)
* Standardize spelling of "publicly" in the codebase …

Ticket drop time UI support, unapproved club event visibility changes

---

backend/clubs/permissions.py
backend/clubs/views.py
backend/tests/clubs/test_views.py
frontend/components/Settings/BulkEditTab.tsx
frontend/pages/admin/[[...slug]].tsx

Adds backend route to email selected populations (e.g. club leaders, officers, or all members). This route's only usable by admins. Also adds frontend UI to admin dashboard.
Closes #783.

Add email blast feature to admin dashboard

---

backend/clubs/views.py
frontend/components/ClubEditPage/ApplicationsPage.tsx
frontend/pages/club/[club]/application/[application]/index.tsx

Some QoL improvements to the application submission management flow for club officers, aiming at reducing user error and increasing clarity for the application decision sending process:
* Add warning toast when sending decisions while having selected applications (route send decisions to all submissions regardless of selection on frontend, so can result in wrong user assumptions about who the updates are sent to)
* Wording changes to emphasize the above fact and warn users against the resend notifications feature
* Route to send application updates now has detail breaking down why certain users were not sent new emails
* (not that related) Putting in non-existent club/application ids into the `/application` route returns a proper X not found screen instead of an empty one

Application submission management clarity

---

backend/clubs/serializers.py
backend/clubs/views.py
backend/pyproject.toml
backend/tests/clubs/test_views.py
backend/uv.lock
frontend/components/ClubPage/Description.tsx
frontend/components/ClubPage/Header.tsx
frontend/components/Settings/QueueTab.tsx

Main features:
- In the admin queue there are now tags denoting whether a club is new or has an updated name/title/description
- If a club is pending approval, administrators now see the difference between the old and new versions. Red highlighting denotes text being removed. Green denotes text being added, and yellow denotes style changes that did not involve the actual content (e.g. changing the font size of text).
Flow:
1. Engineering Student creates a club
2. Engineering student updates description
Admin perspective:
Student perpspective:
Main modifications:
Serializers.py
(1238-1308) - Function for calculating difference between HTML files and visually constructing them
(972 - 1010) - Created a serializer for club-detail-diff function that uses above diff function to add fields for …

Club diff for merge

---

frontend/components/Settings/QueueTab.tsx

I noticed that the frontend PR for ownership requests #815 was calling the  `/api/requests/ownership` endpoint when listing all ownership requests for admins to see. The route that actually provides this functionality is `/clubs/any_club_code/ownershiprequests/all`.  As a result, ownership requests made by users other than the currently logged-in user were not appearing in the admin dashboard. This PR so far just updates the frontend to use the correct route so all relevant ownership requests are displayed.

Fix route for listing all ownership requests

---

frontend/components/ClubEditPage/ClubManagementCard.tsx
frontend/components/ClubPage/Header.tsx
frontend/components/Settings/BulkEditTab.tsx
frontend/components/common/TagGroup.tsx
frontend/components/reports/ReportForm.tsx
frontend/components/reports/ReportPage.tsx
frontend/pages/admin/[[...slug]].tsx
frontend/pages/admin/reports/[report]/index.tsx
frontend/pages/admin/reports/create.tsx
frontend/pages/club/[club]/index.tsx
frontend/pages/events/[id]/index.tsx
frontend/pages/index.tsx
frontend/renderPage.tsx
frontend/types.ts
frontend/utils/branding.tsx

This PR moves from using `badges` to `affilliations` in code and in communication, but maintains references in communication with the backend such as filters and routes. `badges in backend == affiliations on frontend`
Closses #822

Move from badges -> affiliations on frontend only

---

backend/clubs/management/commands/import_paideia_events.py
backend/clubs/serializers.py

#568 
- Sanitize HTML for content rendered via `dangerouslySetInnerHTML` by cleaning on the backend.
- Add allowlist-based sanitization for Club Applications and Club Fairs.
- Sanitize third-party imported event descriptions (SNF Paideia) before saving.

fix: harden HTML sanitization for applications, fairs, and imported events (XSS mitigation)
